### ISSUE TITLE
弗洛妮-s05e02-《2021年，我的一点看法》

### ISSUE THREAD

**Issue by Yibenzhengjing003** [GC4WP/gc5t42#2]
2020发生了太多事，让一直忙忙碌碌，急匆匆向前的人们被迫停下来。

疫情期间宅在家的一个月，全家人吃完了一个冰箱和一个冰柜里的所有食材。(还好住在农村，仓里有粮，地里有菜。)

以为世界在不断向着全球化去的，我们同住一个地球村。谁知道疫情生硬的将人类圈在了各国各省各市各小区。

和美国关系的升级，越发让人看不清未来的方向。

尽管人们貌似在照常生活，但是，还是有很多细微的变化。

囤货这件事在2019年已经被我严令禁止，并且在笔记本显眼的位置写了“禁止囤货，禁止超前消费”的大字用于提醒自己。现代生活的便利程度已经超乎想象，想要购买的日常生活用品和食物要么楼下就有，要么可以当天送达。现代商人一边鼓吹超前消费，一边断舍离。过万一平米的房子不适合堆放杂物。以往，日常消耗品我都是半年一买或者一年一买。可是2020的春节长沙市里的家什么都没有囤，一点儿吃的都没有。现在我的购物指南应该是理智囤货和疯狂存钱吧。

“天有不测风云”，“晴带雨伞，饱带干粮”，只能说这些古话都是前人吃过许多苦积累的教训。真正吃过苦的爷爷辈儿大多都还在世，对饥饿记忆深刻。亲戚家一位快90岁的爷爷，住在农村，现在已经不种地了，可是每年稻子收获的季节他都会买500斤稻谷，大概是他和老伴儿一年吃的米量，就堆他睡觉的房间，觉得踏实。不管子女告诉他现在有多方便，随时可以买米，而且新鲜，这些都不管用，看到，家里有粮，才安心。

今年，算是真正理解了这位爷爷的心情。

我先生家也在农村，是离长沙市40分钟车程的农。家里还分得两亩地，每年会种些稻子自己吃，吃不完卖一些，一些用来喂鸡鸭鹅。今年饭桌上亲戚朋友在一起的话题会有，把稻子都留下来，要囤一点粮食，现在社会这个情况，不知道未来会发生什么。

今年的双十一生意估计会特别好，我家冰箱里的食物都是是常满的状态。今年过年的腊货现在家人商量着也会比往年准备得多。

先生的爷爷今年去世了，享年80岁，很安详的去世。但是发生得很突然，没有一点点预兆。家人们都非常伤心，但是回忆起来，大家都觉得尽了自己最大努力陪伴了，疫情全家人都在家里，四代同堂。休息日节假日都或轮流陪伴或齐聚在一起，天晴的日子还常出门走走，好吃的总会带回家。人与人之间的距离是时间与心思的累积的结果。先生平时工作忙，陪小孩的时间很少，可是这个假期是每天都在一起，游戏，玩耍。亲子关系向前迈进一大步。筹划一日三餐吃什么，一起做准备，平凡却温情的小日子，也算冲刷了现实生活大环境里那么多不如意。

世界在不断变化，我们也马不停蹄向前奔跑，现在有机会让我们停下来想想平凡的生活，让我们首先紧紧抓住手上已拥有的幸福吧。

疯狂存钱，大别野也会有的。

**Comment by ZoomQuiet** [comment]
@Yibenzhengjing003 不好意思, 说错了...

应该是大家都回复到 Issue 中, 
以便投票...

已经链接过去了, 这里先关闭, 
不影响访问.
